### ISSUE TITLE
Monika Cannot Running in Ubuntu 22.04.2

### ISSUE THREAD

**Issue by awcodify** [hyperjumptech/monika#1027]
**Describe the bug**
I got this error when running  `monika-v1.15.1` in `Ubuntu 22.04.2`:

```
awcodify@monika-instatus-test-1:~$ ./monika --version
pkg/prelude/bootstrap.js:1833
      throw error;
      ^

Error: Cannot find module '/snapshot/monika/node_modules/axios/dist/node/axios.cjs'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
    at resolveExports (node:internal/modules/cjs/loader:482:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1912:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1812:31)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'MODULE_NOT_FOUND',
  path: '/snapshot/monika/node_modules/axios/package.json',
  pkg: true
}
```

**To Reproduce**
Run `monika --version`

**Expected behavior**
Return `@hyperjumptech/monika/1.15.1`

**Desktop (please complete the following information):**
Ubuntu 22.04.2

**Comment by awcodify** [comment]
In any case, I tried it on my local machine and encountered the same error.

```
sw_vers
ProductName:		macOS
ProductVersion:		13.0.1
BuildVersion:		22A400
```

**Comment by dennypradipta** [comment]
Hi @awcodify thanks for the report! It seems that upgrading Axios is the root cause of the breaking binaries (which discussed here: [https://github.com/vercel/pkg/issues/1822](https://github.com/vercel/pkg/issues/1822))

I'll see what I can do about this :)

**Comment by dennypradipta** [comment]
Hello, @awcodify could you confirm that the binary is working in v1.15.2?
![image](https://user-images.githubusercontent.com/16670475/231971281-9d6ed068-ebef-4f76-a658-54df18a07390.png)
