### ISSUE TITLE
Config load from URL not working

### ISSUE THREAD

**Issue by luizrojo** [hyperjumptech/monika#981]
**Describe the bug**
While trying to start Monika using a remote configuration file it still looks for a local file with the URL name

**To Reproduce**
1. Have an http endpoint with the config available, in my case I am running a simple python http.server
2. Start Monika point to the configuration file URL `./monika -c http://0.0.0.0:8000/monika.yml`
3. Monika will fail with the following error
```
INFO: Monika is running from: Amsterdam - XXXXXXX - XXXXX (xx.xx.xx.xx)
INFO: You can scrape Prometheus metrics from http://localhost:3001/metrics
INFO: Updating config
error: Error: ENOENT: no such file or directory, open 'http://0.0.0.0:8000/monika.yml'
    at Object.openSync (node:fs:585:3)
    at Object.openSync (pkg/prelude/bootstrap.js:753:32)
    at Object.readFileSync (node:fs:453:35)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1039:36)
    at validateConfigFile (/snapshot/monika/lib/components/config/validate-config.js:41:64)
    at validateConfig (/snapshot/monika/lib/components/config/validate.js:362:72)
    at updateConfig (/snapshot/monika/lib/components/config/index.js:68:57)
    at setupConfig (/snapshot/monika/lib/components/config/index.js:200:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async init (/snapshot/monika/lib/loaders/index.js:65:9)
    at async Monika.run (/snapshot/monika/lib/index.js:93:13)
    at async Monika._run (/snapshot/monika/node_modules/@oclif/core/lib/command.js:67:22) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'http://0.0.0.0:8000/monika.yml'
}
ERROR: ENOENT: no such file or directory, open 'http://0.0.0.0:8000/monika.yml'
    Error: ENOENT: no such file or directory, open 'http://0.0.0.0:8000/monika.yml'
        at Object.openSync (node:fs:585:3)
        at Object.openSync (pkg/prelude/bootstrap.js:753:32)
        at Object.readFileSync (node:fs:453:35)
        at Object.readFileSync (pkg/prelude/bootstrap.js:1039:36)
        at validateConfigFile (/snapshot/monika/lib/components/config/validate-config.js:41:64)
        at validateConfig (/snapshot/monika/lib/components/config/validate.js:362:72)
        at updateConfig (/snapshot/monika/lib/components/config/index.js:68:57)
        at setupConfig (/snapshot/monika/lib/components/config/index.js:200:30)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async init (/snapshot/monika/lib/loaders/index.js:65:9)
        at async Monika.run (/snapshot/monika/lib/index.js:93:13)
        at async Monika._run (/snapshot/monika/node_modules/@oclif/core/lib/command.js:67:22)
```

**Expected behavior**
Monika should load the file from the remote URL and not look for a local file named `http://0.0.0.0:8000/monika.yml`

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Version 13.1

**Comment by sapiderman** [comment]
The example from our docs and help:
```console
monika --config https://raw.githubusercontent.com/hyperjumptech/monika/main/monika.example.yml
```

returns:
![image](https://user-images.githubusercontent.com/964106/217746201-531d7173-66da-45e6-840d-dc4bf8d57d69.png)
